version: "3.7"
services:
  app:
    build:
      args:
        user: ${USER}
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: studiosol
    container_name: studiosol-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - studiosol
  nginx:
    image: nginx:alpine
    container_name: studiosol-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - studiosol

networks:
  studiosol:
    driver: bridge
